# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: The Mind of Eric
email: porter.eric.e@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  I'm an aspiring web developer from Idaho. I'm excited to increase my knowledge and skills to become fully integrated into
  the development profession. I also enjoy hard rock music and photography.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: epix360
github_username:  epix360

# Build settings
markdown: kramdown
